.PHONY : ALL
ALL :  p1 p2 p3 p4 p4p

p1:
	g++ -g -o p1 p1.cc
p2:
	g++ -g -o p2 p2.cc
p3:
	g++ -g -o p3 p3.cc
p4:
	g++ -g -o p4 p4.cc
p4p:
	g++ -g -o p4p p4p.cc

.PHONY : clean
clean : 
	 rm -rf  p1 p2 p3 p4 p4p
