.PHONY : ALL
ALL :  p10 p1 p2 p3 p4 p4p p7 p8

p10:
	g++ -g -o p10 p10.cc
p1:
	g++ -g -o p1 p1.cc
p2:
	g++ -g -o p2 p2.cc
p3:
	g++ -g -o p3 p3.cc
p4:
	g++ -g -o p4 p4.cc
p4p:
	g++ -g -o p4p p4p.cc
p7:
	g++ -g -o p7 p7.cc
p8:
	g++ -g -o p8 p8.cc

.PHONY : clean
clean : 
	 rm -rf  p10 p1 p2 p3 p4 p4p p7 p8
